language: cpp
version: ~> 1.0
cache:
    apt: true
    ccache: true
    directories:
        - toolchain
        - /tmp/libpfm
    timeout: 1000
os:
    - linux
dist: bionic
compiler:
    - gcc
addons:
    apt:
        update: true
        packages:
            - cmake
            - cmake-data
            - shellcheck
            - linux-tools-generic
            - zlib1g-dev
notifications:
    email:
        on_success: change
        on_failure: always
env:
    global:
        - CHOPSTIX_PERFMON_PREFIX=/tmp/libpfm
        - CTEST_OUTPUT_ON_FAILURE=1
stages:
  - shell_conventions
  - build_and_test
  - test
  - install
jobs:                                                                              
    fast_finish: true                                                              
    include:
        - stage: shell_conventions                                                 
          name: shell conventions amd64                                              
          cache: false                                                             
          arch: amd64
          script:                                                                  
              - set -e                                                             
              - shellcheck -x -s sh $(find . -name \*.sh) $(find . -name \*.sh.in) ./tools/chop-* ./test/drivers/* ./test/daxpy/*spec
        - stage: shell_conventions                                                 
          name: shell conventions ppc64le                                                 
          cache: false                                                             
          arch: ppc64le
          script:                                                                  
              - set -e                                                             
              - shellcheck -x -s sh $(find . -name \*.sh) $(find . -name \*.sh.in) ./tools/chop-* ./test/drivers/* ./test/daxpy/*spec
        - stage: shell_conventions                                                 
          name: shell conventions s390x                                           
          cache: false                                                             
          arch: s390x
          script:                                                                  
              - set -e                                                             
              - shellcheck -x -s sh $(find . -name \*.sh) $(find . -name \*.sh.in) ./tools/chop-* ./test/drivers/* ./test/daxpy/*spec
        - stage: build_and_test
          name: Build and test amd64
          arch: amd64
          script:
              - set -e
              - scripts/ci/install_libpfm.sh
              - echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid 
              - mkdir build
              - cd build
              - ../configure
              - make -j2
              - make test
              - sudo make install
        - stage: build_and_test
          name: Build and test ppc64le
          arch: ppc64le 
          script:
              - set -e
              - scripts/ci/install_libpfm.sh
              - echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid 
              - mkdir build
              - cd build
              - ../configure
              - make -j2
              - make test
              - sudo make install
        - stage: build_and_test
          name: Build and test s390x
          arch: s390x
          script:
              - set -e
              - scripts/ci/install_libpfm.sh
              - echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid 
              - mkdir build
              - cd build
              - ../configure
              - make -j2
              - make test
              - sudo make install
        - stage: test
          name: Test
          script:
              - set -e
              - echo "Test"
              - cd build
              - make test
        - stage: install
          name: Install
          script:
              - set -e
              - echo "Install ChopStiX"
              - cd build
              - sudo make install
