language: cpp
version: ~> 1.0
cache:
    apt: true
    ccache: true
    directories:
        - toolchain
        - /tmp/libpfm
    timeout: 1000
os:
    - linux
dist: bionic
compiler:
    - gcc
addons:
    apt:
        update: true
        packages:
            - cmake
            - cmake-data
            - shellcheck
            - linux-tools-generic
            - zlib1g-dev
            - g++-11
            - gcc-11
            - libopenblas-dev
            - libatlas-base-dev
            - liblapack-dev
            - python3
            - python3-pip
            - python3-virtualenv
            - python3-scipy
            - python3-sklearn
            - python3-dev
            - gfortran-11
            - gfortran
            - build-essential 
        sources:
            - ubuntu-toolchain-r-test
notifications:
    email:
        on_success: change
        on_failure: always
env:
    global:
        - CHOPSTIX_PERFMON_PREFIX=/tmp/libpfm
        - CTEST_OUTPUT_ON_FAILURE=1
        - CC=gcc-11
        - CXX=g++-11
        - FC=gfortran-11
        - CFLAGS="-fno-lto"
        - CXXFLAGS="-fno-lto"
        - LDFLAGS="-fno-lto"
stages:
  - shell_conventions
  - build_and_test
  - test
  - install
jobs:                                                                              
    fast_finish: true                                                              
    include:
        - stage: shell_conventions                                                 
          name: shell conventions amd64                                              
          arch: amd64
          script:                                                                  
              - set -e                                                             
              - shellcheck -x -s sh $(find . -name \*.sh) $(find . -name \*.sh.in) ./tools/chop-* ./test/drivers/* ./test/daxpy/*spec
        - stage: shell_conventions                                                 
          name: shell conventions ppc64le                                                 
          arch: ppc64le
          script:                                                                  
              - set -e                                                             
              - shellcheck -x -s sh $(find . -name \*.sh) $(find . -name \*.sh.in) ./tools/chop-* ./test/drivers/* ./test/daxpy/*spec
        - stage: shell_conventions                                                 
          name: shell conventions s390x                                           
          arch: s390x
          script:                                                                  
              - set -e                                                             
              - shellcheck -x -s sh $(find . -name \*.sh) $(find . -name \*.sh.in) ./tools/chop-* ./test/drivers/* ./test/daxpy/*spec
        - stage: build_and_test
          name: Build and test amd64
          arch: amd64
          script:
              - set -e
              - scripts/ci/install_libpfm.sh
              - mkdir build
              - cd build
              - ../configure --prefix /tmp/install
              - make -j
              - make test
              - pip install -U pip virtualenv
              - make install
        - stage: build_and_test
          name: Build and test ppc64le
          arch: ppc64le 
          script:
              - set -e
              - scripts/ci/install_libpfm.sh
              - mkdir build
              - cd build
              - ../configure --prefix /tmp/install
              - make -j
              - make test
              - pip3 install -U pip virtualenv
              - make install
        - stage: build_and_test
          name: Build and test s390x
          arch: s390x
          script:
              - set -e
              - scripts/ci/install_libpfm.sh
              - mkdir build
              - cd build
              - ../configure --prefix /tmp/install
              - make -j
              - make test
              - pip3 install -U pip virtualenv
              - make install
