#!/usr/bin/env sh
#
# ----------------------------------------------------------------------------
#
# Copyright 2019 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ----------------------------------------------------------------------------
#

set -eu

die() { echo "$*" >&2 ; exit 1 ; }

test=$(printenv test)
chop=$(printenv chop)
testbin=$(printenv testbin)
testdir=$(printenv testdir)

test_run() {
    ver="$1" ; shift
    echo "> test-$test $* ($ver)"
    timeout "$TIMEOUT $testbin $*" > "output.$ver" || die "Error: test failed"
}

test_trace_function() {
    fun="$1" ; shift
    rm -rf chop.db
    echo "> chop trace function -name $fun test-$test $*"
    timeout "$TIMEOUT $chop trace function -name $fun $testbin $*" > "output.trace-$fun" || die "Error: test failed"
}

test_trace() {
    fun="$1" ; shift
    rm -rf chop.db
    objdump -d "$testbin" > "test-$test.s"
    args=$(awk -v fun="$fun" '
    $0 ~ fun">:" { gsub(/^0*/,"",$1); begin=$1; flag=1 }
    flag && /\sret/ { gsub(/:/,"",$1); end=","$1 }
    /^$/ { flag = 0 }
    END { gsub(/^,/,"",end); print "-begin",begin,"-end",end }
    ' "test-$test.s")
    echo "> chop trace $args test-$test $*"
    timeout "$TIMEOUT $chop trace address $args $testbin $*" > "output.trace-$fun" || die "Error: test failed"

}

validate_output() {
    diff -I '#.*' -q "output.$1" "output.$2"
    echo "> output matches"
}

export TIMEOUT=10s

# shellcheck disable=SC1090,SC1091
. "$testdir/trace.spec"
