function (prepend_path var prefix)
    unset (tmp)
    foreach (f ${${var}})
        message (STATUS "Debug: ${f}")
        list (APPEND tmp "${prefix}/${f}")
    endforeach (f)
    message (STATUS "Temp: ${tmp}")
    set (${var} ${tmp} PARENT_SCOPE)
endfunction (prepend_path)
