#!/usr/bin/env sh
#
# ----------------------------------------------------------------------------
#
# Copyright 2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ----------------------------------------------------------------------------
#

set -e
scriptpath=$( cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P )
machine=$(uname -m)

if [ "$machine" = "riscv64" ]; then
    marks_cmd=chop-marks-riscv
elif [ "$machine" = "ppc64le" ]; then
    marks_cmd=chop-marks-ppc64
elif [ "$machine" = "s390x" ]; then
    marks_cmd=chop-marks-sysz
else
    echo "Unsupported architecture: $machine"
    cleanup
    exit 0
fi

# shellcheck disable=SC2068
"$scriptpath/$marks_cmd" $@
