#!/usr/bin/env bash
#
# ----------------------------------------------------------------------------
#
# Copyright 2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ----------------------------------------------------------------------------
#

set -e # Finish right after a non-zero return command

EXECUTABLE=$1
FUNCTION=$2

find_ret_address () {
    objdump --disassemble="$1" "$EXECUTABLE" | grep -w "ret" | cut -d":" -f 1 | awk '{ printf "%s %s", sep, $0 ; sep="," } END { print "" }' | tr -d ' '
}

BEGIN=$(nm "$EXECUTABLE" | grep -w "$FUNCTION" -m 1 | cut -d" " -f 1)
END=$(find_ret_address "$FUNCTION")

if [ -z "$END" ]
then
    NEXT_FUNC=$(nm --numeric-sort --defined-only "$EXECUTABLE" | awk -F" " '$1!=""&&$2!=""&&$3!=""' | grep -A 1 "$FUNCTION" | tail -n 1 | cut -d" " -f 3)
    END=$(find_ret_address "$NEXT_FUNC")
fi

# shellcheck disable=SC2039
printf -- "-begin %s" "$BEGIN"

# shellcheck disable=SC3060,SC2039
for addr in ${END//,/ }; do
    printf -- " -end %s" "$addr"
done

printf "\n"
