#!/bin/sh

set -e # Finish right after a non-zero return command

EXECUTABLE=$1
FUNCTION=$2

find_ret_address () {
    objdump --disassemble="$1" "$EXECUTABLE" | grep -w "ret" | cut -d":" -f 1 | awk '{ printf "%s%s", sep, $0 ; sep="," } END { print "" }' | tr -d ' '
}

BEGIN=$(nm "$EXECUTABLE" | grep -w "$FUNCTION" -m 1 | cut -d" " -f 1)
END=$(find_ret_address "$FUNCTION")

if [ -z "$END" ]
then
    NEXT_FUNC=$(nm --numeric-sort --defined-only "$EXECUTABLE" | awk -F" " '$1!=""&&$2!=""&&$3!=""' | grep -A 1 "$FUNCTION" | tail -n 1 | cut -d" " -f 3)
    END=$(find_ret_address "$NEXT_FUNC")
fi

echo "-begin $BEGIN -end $END"
